CREATE DATABASE WELLINGTONA3;

USE WELLINGTONA3;


CREATE TABLE ENDERECO (
ENT_INT_ID INT,
CLI_INT_ID INT,
CID_INT_ID INT,
END_INT_ID INT NOT NULL IDENTITY(1,1),
END_STR_RUA VARCHAR (25) NOT NULL,
END_STR_NUM_CASA VARCHAR (20) NOT NULL,
END_STR_CEP VARCHAR (20) NOT NULL,
END_STR_COM VARCHAR (20) NOT NULL,
END_CHAR_EST CHAR(2) NOT NULL,
CONSTRAINT PK_ENDERECO_ID PRIMARY KEY (END_INT_ID),
CONSTRAINT UK_ENDERECO_EST UNIQUE (END_CHAR_EST),
);

CREATE TABLE ENDERECO_TIPO (
ENT_INT_ID INT NOT NULL IDENTITY(1,1),
ENT_STR_DESC VARCHAR (25) NOT NULL,
CONSTRAINT PK_ENDERECO_TIPO_ID PRIMARY KEY (ENT_INT_ID),
);

CREATE TABLE ESTADO (
EST_INT_ID INT NOT NULL IDENTITY (1,1),
EST_CHAR_SIG CHAR(2)
CONSTRAINT UK_ESTADO_SIGLA UNIQUE (EST_CHAR_SIG),
CONSTRAINT PK_ESTADO_ID PRIMARY KEY (EST_INT_ID),
);

CREATE TABLE CIDADE (
EST_INT_ID INT,
CID_INT_ID INT NOT NULL IDENTITY(1,1),
CID_STR_DESC VARCHAR (50) NOT NULL,
CID_STR_NOME VARCHAR (50) NOT NULL,
CONSTRAINT PK_CIDADE_ID PRIMARY KEY (CID_INT_ID),
);

CREATE TABLE FORNECEDOR (
FORT_INT_ID INT,
FORN_INT_ID INT NOT NULL IDENTITY(1,1),
FORN_STR_RAZAO_SOCIAL VARCHAR(50) NOT NULL,
FORN_INT_CNPJ CHAR(14) NOT NULL,
FORN_STR_ENDERECO VARCHAR(50) NOT NULL,
FORN_INT_TELEFONE INT NOT NULL,
FORN_STR_PESSOA_CONTATO VARCHAR(50) NOT NULL,
CONSTRAINT PK_FORNECEDOR_ID PRIMARY KEY (FORN_INT_ID),
CONSTRAINT UK_FORNECEDOR_CNPJ UNIQUE (FORN_INT_CNPJ),
CONSTRAINT UK_FORNECEDOR_RAZAO_SOCIAL UNIQUE (FORN_STR_RAZAO_SOCIAL)
);

CREATE TABLE FORNECEDOR_TIPO (
FORT_INT_ID INT NOT NULL IDENTITY(1,1),
FORT_STR_DESC VARCHAR(45) NOT NULL,
CONSTRAINT PK_FORNECEDOR_TIPO_ID PRIMARY KEY (FORT_INT_ID),
);

CREATE TABLE COMPONENTE_FORNECEDOR (
COM_INT_ID INT,
FORN_INT_ID INT,
COF_INT_ID INT NOT NULL IDENTITY(1,1),
COF_STR_DESC VARCHAR(50) NOT NULL,
COF_STR_DATA_FORNECIMENTO DATE NOT NULL,
COF_STR_CONDICAO_ENTREGA VARCHAR(100) NOT NULL,
CONSTRAINT PK_COMPONENTE_FORNECEDOR_ID PRIMARY KEY ( COF_INT_ID ),
);

CREATE TABLE ENCOMENDA (
CLI_INT_ID INT,
ENC_INT_ID INT NOT NULL IDENTITY(1,1),
ENC_STR_NUMERO_ENCOMENDA INT NOT NULL,
ENC_DATE_INCLUSAO DATE NOT NULL,
ENC_STR_VALOR_TOTAL INT NOT NULL,
ENC_STR_DESCONTO INT NOT NULL,
ENC_STR_VALOR_LIQUIDO INT NOT NULL,
ENC_STR_FORMA_PAGAMENTO VARCHAR (50) NOT NULL,
CONSTRAINT PK_ENCOMENDA_ID PRIMARY KEY (ENC_INT_ID),
CONSTRAINT UK_NUMERO_ENCOMENDA UNIQUE (ENC_STR_NUMERO_ENCOMENDA)
);

CREATE TABLE PRODUTO(
PRO_INT_ID INT NOT NULL IDENTITY(1,1),
PRO_NOME_STR VARCHAR(20) NOT NULL,
PRO_CODIGO INT NOT NULL,
PRO_COR_STR VARCHAR(20) NOT NULL,
PRO_DIMENSOES_STR VARCHAR(45) NOT NULL,
PRO_PESO INT NOT NULL,
PRO_PRECO INT NOT NULL,
PRO_TEMPO_FABRICACAO INT NOT NULL,
PRO_STR_DESENHO VARCHAR (50) NOT NULL,
CONSTRAINT PK_PRO_ID PRIMARY KEY (PRO_INT_ID),
CONSTRAINT UK_PRO_CODIGO UNIQUE (PRO_CODIGO)
);

CREATE TABLE COMPONENTE(
ESQ_INT_ID INT,
COM_INT_ID INT NOT NULL IDENTITY(1,1),
COM_TIPO_INT_ID INT,
COM_NOME_STR VARCHAR(20) NOT NULL,
COM_CODIGO INT NOT NULL,
COM_STR_QUANTIDADE VARCHAR(20) NOT NULL,
COM_PRECO_UNITARIO_INT INT NOT NULL,
CONSTRAINT PK_COMPONENTE_ID PRIMARY KEY (COM_INT_ID),
CONSTRAINT UK_COM_CODIGO UNIQUE (COM_CODIGO)
);

CREATE TABLE PRODUTO_COMPONENTE(
COM_INT_ID INT,
PRO_INT_ID INT,
PROC_INT_ID INT NOT NULL IDENTITY(1,1),
PROC_QUANTIDADE_NECESSARIA_STR INT NOT NULL,
PROC_UNIDADE_MEDIDA_CHAR CHAR(10) NOT NULL,
PROC_DATE_USO_MAQUINA DATE NOT NULL,
CONSTRAINT PK_PRODUTO_COMPONENTE_ID PRIMARY KEY ( PROC_INT_ID )
);

CREATE TABLE COMPONENTE_TIPO(
COM_TIPO_INT_ID INT NOT NULL IDENTITY(1,1),
COM_TIPO_DESCRICAO_STR VARCHAR(20) NOT NULL,
CONSTRAINT PK_COM_TIPO_ID PRIMARY KEY (COM_TIPO_INT_ID),
);

CREATE TABLE CLIENTE(
CLI_INT_ID INT NOT NULL IDENTITY(1,1),
CLI_PESSOA_CONTATO VARCHAR(45) NOT NULL,
CLI_CNPJ_INT CHAR(14) NOT NULL,
CLI_GMAIL_STR VARCHAR(45) NOT NULL,
CLI_TELEFONE_INT VARCHAR(20) NOT NULL,
CLI_RAZAO_SOCIAL_STR VARCHAR(45) NOT NULL,
CLI_RAMO_ATIVIDADE_STR VARCHAR(20) NOT NULL,
CLI_DATA_CADASTRO_DATA DATE NOT NULL,
CONSTRAINT PK_PESSOA_CONTATO PRIMARY KEY (CLI_INT_ID),
CONSTRAINT UK_CLIENTE_CNPJ UNIQUE (CLI_CNPJ_INT)
);

CREATE TABLE EMPREGADO_MAO_OBRA(
EMPM_INT_ID INT NOT NULL IDENTITY(1,1),
END_INT_ID INT NOT NULL,
EMP_MAO_OBRA_ID INT NOT NULL,
EMP_MATRICULA_INT INT NOT NULL,
EMP_NOME_STR VARCHAR(70) NOT NULL,
EMP_ENDERECO_STR VARCHAR(100) NOT NULL,
EMP_TELEFONE_INT INT NOT NULL,
EMP_CARGO_STR VARCHAR(50) NOT NULL,
EMP_SALARIO_INT INT NOT NULL,
EMP_DATA_ADMISSAO DATE NOT NULL,
EMP_QUALIFICACAO_STR VARCHAR(50) NOT NULL,
EMP_SUPERIOR_STR VARCHAR(50) NOT NULL,
CONSTRAINT PK_EMPM_ID PRIMARY KEY (EMPM_INT_ID),
CONSTRAINT UK_EMP_MATRICULA_ID UNIQUE (EMP_MATRICULA_INT)
);

CREATE TABLE MANUTENCAO (
MAN_INT_ID INT NOT NULL IDENTITY(1,1),
MAQ_INT_ID INT NOT NULL,
MAN_DATA_MANUTENCAO DATE NOT NULL,
MAN_DESCRICAO_STR VARCHAR(45) NOT NULL,
CONSTRAINT PK_MANUTENCAO_ID PRIMARY KEY (MAN_INT_ID)
);

CREATE TABLE MAQUINA(
MAQ_INT_ID INT NOT NULL IDENTITY(1,1),
COM_INT_ID INT,
MAQ_CODIGO_INT INT NOT NULL,
MAQ_TEMPO_VIDA_DATE DATE NOT NULL,
MAQ_DATA_COMPRA_DATE DATE NOT NULL,
MAQ_DATA_GARANTIA DATE NOT NULL,
CONSTRAINT PK_ID_MAQUINA PRIMARY KEY (MAQ_INT_ID),
CONSTRAINT UK_MAQUINA_FERRAMENTA UNIQUE (MAQ_CODIGO_INT)
);

CREATE TABLE ENCOMENDA_PRODUTO (
ENCP_INT_ID INT NOT NULL IDENTITY (1,1),
PRO_INT_ID INT,
ENC_INT_ID INT,
ENCP_DATE_PRAZO DATE NOT NULL,
ENCP_INT_QUANTIDADE INT NOT NULL,
ENCP_INT_PRECO_UNITARIO INT NOT NULL,
CONSTRAINT PK_ENCOMENDA_PRDUTO_ID PRIMARY KEY (ENCP_INT_ID)
);

CREATE TABLE ESTOQUE (
PRO_INT_ID INT,
COM_INT_ID INT,
ESQ_INT_ID INT NOT NULL IDENTITY (1,1),
ESQ_STR_DESC VARCHAR (50) NOT NULL,
ESQ_INT_QUANTIDADE VARCHAR(50) NOT NULL,
ESQ_STR_SETOR VARCHAR(20) NOT NULL,
ESQ_INT_MAX INT NOT NULL,
ESQ_DATE_ENTRADA DATE NOT NULL,
ESQ_DATE_SAIDA DATE NOT NULL,
CONSTRAINT PK_ESTOQUE_ID PRIMARY KEY (ESQ_INT_ID)
);

CREATE TABLE MADEIRA_VERDE (
COMT_INT_ID INT,
END_INT_ID INT,
MAD_INT_ID INT IDENTITY (1,1),
MAD_INT_CNPJ CHAR (14) NOT NULL,
MAD_STR_RAZAO_SOCIAL VARCHAR(50) NOT NULL,
CONSTRAINT PK_MADEIRA_VERDE_ID PRIMARY KEY (MAD_INT_ID),
CONSTRAINT UK_MADEIRA_VERDE_CNPJ UNIQUE (MAD_INT_CNPJ),
CONSTRAINT UK_MADEIRA_VERDE_RAZAO_SOCIAL UNIQUE (MAD_STR_RAZAO_SOCIAL)
);

CREATE TABLE COMPRA (
CLI_INT_ID INT,
PRO_INT_ID INT,
COMT_INT_ID INT,
COMP_INT_ID INT IDENTITY (1,1) NOT NULL,
COMP_STR_DESC VARCHAR(100) NOT NULL,
COMP_INT_NF INT NOT NULL,
CONSTRAINT PK_COMPRA_ID PRIMARY KEY (COMP_INT_ID)
);

CREATE TABLE COMPRA_TIPO (
COMT_INT_ID INT IDENTITY (1,1) NOT NULL,
COMT_STR_DESC VARCHAR(100) NOT NULL,
COMT_INT_NF INT NOT NULL,
CONSTRAINT PK_COMPRA_TIPO_ID PRIMARY KEY (COMT_INT_ID)
);

CREATE TABLE VENDE (
MADEIRA_VERDE_ID INT,
PRO_INT_ID INT,
VEN_INT_ID INT NOT NULL IDENTITY(1,1),
VEN_INT_VALOR INT NOT NULL,
VEN_STR_DESC VARCHAR(100) NOT NULL,
);

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_END_TIPO_ENDERECO_ID
FOREIGN KEY ( ENT_INT_ID )
REFERENCES ENDERECO_TIPO ( ENT_INT_ID );

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_CIDADE_ENDERECO_ID
FOREIGN KEY ( CID_INT_ID )
REFERENCES CIDADE ( CID_INT_ID );

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_CLIENTE_ENDERECO_ID
FOREIGN KEY ( CLI_INT_ID )
REFERENCES CLIENTE ( CLI_INT_ID );

ALTER TABLE CIDADE
ADD CONSTRAINT FK_ESTADO_CIDADE_ID
FOREIGN KEY ( EST_INT_ID )
REFERENCES ESTADO ( EST_INT_ID );

ALTER TABLE FORNECEDOR
ADD CONSTRAINT FK_FORN_TIPO_FORNECEDOR_ID
FOREIGN KEY ( FORT_INT_ID )
REFERENCES FORNECEDOR_TIPO ( FORT_INT_ID );

ALTER TABLE COMPONENTE_FORNECEDOR
ADD CONSTRAINT FK_FORN_COMPONENTE_FORNECEDOR_ID
FOREIGN KEY ( FORN_INT_ID )
REFERENCES FORNECEDOR ( FORN_INT_ID );

ALTER TABLE COMPONENTE_FORNECEDOR
ADD CONSTRAINT FK_COM_COMPONENTE_FORNECEDOR_ID
FOREIGN KEY ( COM_INT_ID )
REFERENCES COMPONENTE ( COM_INT_ID );

ALTER TABLE ENCOMENDA
ADD CONSTRAINT FK_ENCOMENDA_CLIENTE_ID
FOREIGN KEY ( CLI_INT_ID )
REFERENCES CLIENTE ( CLI_INT_ID );

ALTER TABLE PRODUTO_COMPONENTE
ADD CONSTRAINT FK_PRODUTO_PRODUTO_COMPONENTE_ID
FOREIGN KEY (PRO_INT_ID)
REFERENCES PRODUTO (PRO_INT_ID);

ALTER TABLE PRODUTO_COMPONENTE
ADD CONSTRAINT FK_COMPONENTE_PRODUTO_COMPONENTE_ID
FOREIGN KEY (COM_INT_ID)
REFERENCES COMPONENTE (COM_INT_ID);

ALTER TABLE COMPONENTE
ADD CONSTRAINT FK_COMPONENTE_INT_ID
FOREIGN KEY (COM_TIPO_INT_ID)
REFERENCES COMPONENTE_TIPO (COM_TIPO_INT_ID);

ALTER TABLE EMPREGADO_MAO_OBRA
ADD CONSTRAINT FK_EMPREGADO_ENDERECO_ID
FOREIGN KEY ( END_INT_ID )
REFERENCES ENDERECO ( END_INT_ID);

ALTER TABLE MANUTENCAO
ADD CONSTRAINT FK_ID_MANUTENCAO
FOREIGN KEY (MAQ_INT_ID)
REFERENCES MAQUINA ( MAQ_INT_ID );

ALTER TABLE MAQUINA
ADD CONSTRAINT FK_MAQ_COMPONENTE_ID
FOREIGN KEY ( COM_INT_ID )
REFERENCES COMPONENTE ( COM_INT_ID );

ALTER TABLE EMPREGADO_MAO_OBRA
ADD CONSTRAINT FK_EMPM_INT_ID
FOREIGN KEY ( END_INT_ID )
REFERENCES ENDERECO ( END_INT_ID );

ALTER TABLE ENCOMENDA_PRODUTO
ADD CONSTRAINT FK_PRODUTO_ENCOMENDA_PRODUTO_ID
FOREIGN KEY (PRO_INT_ID)
REFERENCES PRODUTO (PRO_INT_ID);

ALTER TABLE ENCOMENDA_PRODUTO
ADD CONSTRAINT FK_ENC_ENCOMENDA_PRODUTO_ID
FOREIGN KEY (ENC_INT_ID)
REFERENCES ENCOMENDA (ENC_INT_ID);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_PRODUTO_ESTOQUE_ID
FOREIGN KEY (PRO_INT_ID)
REFERENCES PRODUTO (PRO_INT_ID);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_COMPONENTE_PRODUTO_ID
FOREIGN KEY (COM_INT_ID)
REFERENCES COMPONENTE (COM_INT_ID);

ALTER TABLE COMPRA
ADD CONSTRAINT FK_COM_COMPRA_TIPO_ID
FOREIGN KEY (COMP_INT_ID)
REFERENCES COMPRA_TIPO (COMP_INT_ID);

ALTER TABLE COMPRA
ADD CONSTRAINT FK_COMPRA_CLIENTE_ID
FOREIGN KEY (CLI_INT_ID)
REFERENCES CLIENTE (CLI_INT_ID);

ALTER TABLE COMPRA
ADD CONSTRAINT FK_COMPRA_PRODUTO_ID
FOREIGN KEY (PRO_INT_ID)
REFERENCES PRODUTO (PRO_INT_ID);

ALTER TABLE COMPONENTE
ADD CONSTRAINT FK_COMPONENTE_ESTOQUE_ID
FOREIGN KEY (ESQ_INT_ID)
REFERENCES ESTOQUE (ESQ_INT_ID);

ALTER TABLE MADEIRA_VERDE
ADD CONSTRAINT FK_MADEIRA_VERDE_COMPRA_ID
FOREIGN KEY (COMT_INT_ID)
REFERENCES COMPRA (COMT_INT_ID);

ALTER TABLE MADEIRA_VERDE
ADD CONSTRAINT FK_MADEIRA_ENDEREÇO_ID
FOREIGN KEY (END_INT_ID)
REFERENCES ENDERECO (END_INT_ID);

ALTER TABLE VENDE
ADD CONSTRAINT FK_MADEIRA_VERDE_VENDE_ID
FOREIGN KEY (MADEIRA_VERDE_ID)
REFERENCES MADEIRA_VERDE (MAD_INT_ID);

ALTER TABLE VENDE
ADD CONSTRAINT FK_PRODUTO_VENDE_ID
FOREIGN KEY (PRO_INT_ID)
REFERENCES PRODUTO (PRO_INT_ID);
